---
abstract: 'Perl module for building clients and servers which resolve and perform metadata queries on LSIDs.'
author: 'IBM <http://lsid.sourceforge.net/>'
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: cpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: lsid-perl
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  Compress::Zlib: 1.22
  Error: 0.15
  File::Copy: 2.01
  File::Temp: 0.12
  LWP: 5.53
  MIME::Base64: 2.12
  MIME::Tools: 6.106
  Net::DNS: 0.28
  Net::FTP: 2.65
  RDF::Core: 0.30
  SOAP::Lite: 0.69
  Time::HiRes: 1.20
  URI: 1.21
  XML::XPath: 1.12
  perl: 5.6.0
version: 1.1.6
